name: Run the qodo-cover action (Python)

on:
  workflow_dispatch:
    inputs:
      desired_coverage:
        description: "Desired coverage percentage"
        required: false
        default: "70"

permissions:
  pull-requests: write
  contents: write

jobs:
  run-qodo-cover-python:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-dev python3-pip
          python3 --version

      - name: Install app dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python3 -m pip install pytest

      - name: Qodo Cover
        uses: qodo-ai/qodo-ci/.github/actions/qodo-cover@v0.1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          project_language: python
          project_root: .
          code_coverage_report_path: ./coverage.xml
          coverage_type: cobertura
          test_command: "pytest --cov=. --cov-report=xml --cov-report=term" # your test command
          model: gpt-4o
          max_iterations: 3
          desired_coverage: 90
          run_each_test_separately: true
          source_folder: so4t_api
          test_folder: tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
